### PR TITLE
Mini dashboard

### PR DESCRIPTION
**Pull request by Tokyo-Viddy**
Changed the left-most menu from going to the home page (which is a useless route for logged-in users in my opinion) to a mini dashboard drop-down.

### CODE REVIEW

**Comment by neoke20** [comment]
Sorry Viddy, this left icon will become the logo that Sae designs over the weekend, and its only purpose is to redirect people to the homepage (or eventually to the dashboard itself which seems more user friendly). Because of that, putting a dropdown menu below the logo is not really the best thing, as user are used to click top left to go back to root in practice.

**Comment by Tokyo-Viddy** [comment]
What is the point of going back to the homepage as a signed-in user? I fail to see why anyone would want to go to the homepage.

**Comment by neoke20** [comment]
Which is why I mentioned _"or eventually to the dashboard itself which seems more user friendly"_ because I think it would be best indeed to not return to the homepage.
But I believe we do not need a mini dashboard below what will become the logo of the website.
We could eventually apply your logic to the top right menu and give a mini dashboard there.

**Comment by Tokyo-Viddy** [comment]
I think eliminating a page for the user by giving the dashboard options instead of routing to the dashboard would be better for UX.

**Comment by neoke20** [comment]
> I think eliminating a page for the user by giving the dashboard options instead of routing to the dashboard would be better for UX.

Yes, and I agree with that, which is why I said the drop-down menu you have created could be placed below the top right menu we have now (the cogs icon). But not really below the logo that Sae just made and that is waiting to be merged. In turn, this logo who is currently redirecting to the homepage, could be left that way, or redirect to the dashboard directly as it would be more user friendly.

**Comment by Tokyo-Viddy** [comment]
So how many things will we have on the navbar?

**Pull request merged**
